{% set name = "libqglviewer" %}
{% set version = "2.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/GillesDebunne/libQGLViewer/archive/refs/tags/v{{ version }}.tar.gz
    sha256: ea4f9ac627c136a6851ffd3763b154f21c87a58bcec4e5d5b2d07e65a403096b
    patches:
      - fix_build.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('libqglviewer', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make                           # [not win]
    - sed                            # [not win]
    - jom                            # [win]
    # x11 stuff
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('expat-devel') }}       # [linux]
  host:
    - libglu                         # [linux]
    - qt-main
  run:
    - libglu                         # [linux]

test:
  commands:
    - test -f $PREFIX/include/QGLViewer/qglviewer.h  # [unix]
    - test -f $PREFIX/lib/libQGLViewer$SHLIB_EXT     # [unix]
    - if exist %PREFIX%\\Library\\include\\QGLViewer\qglviewer.h (exit 0) else (exit 1)  # [win]

about:
  home: http://libqglviewer.com
  license: GPL-2.0-only OR GPL-3.0-only
  license_file: GPL_EXCEPTION
  summary: libQGLViewer is a C++ library based on Qt that eases the creation of OpenGL 3D viewers

extra:
  recipe-maintainers:
    - Tobias-Fischer
